site_name: "Community Data Standards Metadata Schema Documentation"
site_url: https://alleninstitute.github.io/CDS-metadata-schemas/
repo_url: https://alleninstitute.github/CDS-metadata-schemas
repo_name: 'GitHub'
site_description: Documentation for the Community Data Standards Metadata Schema, providing guidelines and standards for metadata management
site_author: Community Data Standards Team
remote_branch: gh-pages
remote_name: origin

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: white
  features:
    - content.tabs.link
plugins: 
  - search
  - mermaid2

nav:
  - Overview: index.md
  - Standards:
      - Overview: Standards/overview.md
      - Data Standards:
          - Introduction: Standards/Data Standards/introduction.md
      - Metadata Standards:
          - Introduction: Standards/Metadata Standards/introduction.md
          - Cell Types Nomenclature Standard: Standards/Metadata Standards/Cell Types Nomenclature Standard.md
          - Digital Asset Types (file types): Standards/Metadata Standards/Digital Asset Types (file types).md
          - Modalities: Standards/Metadata Standards/Modalities.md
          - Specimens: Standards/Metadata Standards/Specimens.md
          - Digital Asset Types (file types): Standards/Metadata Standards/Digital Asset Types (file types).md
          - Process Types (Taxonomy): Standards/Metadata Standards/Process Types (Taxonomy).
          - Experimental Techniques: Standards/Metadata Standards/Experimental Techniques.md
          - Species: Standards/Metadata Standards/Species.md
  - Tools:
      - Overview: Tools/overview.md
  - Controlled Vocabularies:
      - Overview: Controlled Vocabularies/overview.md
      - Techniques: Controlled Vocabularies/techniques_CV.csv
      - Species: Controlled Vocabularies/species_CV.csv
      - Modalities: Controlled Vocabularies/modalities_CV.csv
      - Digital Asset Types CV: Controlled Vocabularies/Digital Asset Types CV.csv
  - Best Practices:
      - Overview: Best Practices/overview.md
      - From Ontology to CV: Best Practices/From Ontology to CV.md
      - How to request a CV term: Best Practices/How to request a CV term.md
  - Case Studies:
      - Overview: Case Studies/overview.md
  - Resources:
      - Documentation: Resources/documentation.md
      - Community: Resources/community.md
  - FAQ: faq.md
  - Contact: contact.md
